// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NextStep.Infrastructure.Persistence;

#nullable disable

namespace NextStep.Infrastructure.Migrations
{
    [DbContext(typeof(NextStepDbContext))]
    [Migration("20260201180322_AddTrainingAvailability")]
    partial class AddTrainingAvailability
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("NextStep.Domain.AthleteProfile.Entities.Athlete", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Athletes", (string)null);
                });

            modelBuilder.Entity("NextStep.Domain.AthleteProfile.Entities.Athlete", b =>
                {
                    b.OwnsOne("NextStep.Domain.AthleteProfile.ValueObjects.PersonalInfo", "PersonalInfo", b1 =>
                        {
                            b1.Property<Guid>("AthleteId")
                                .HasColumnType("char(36)");

                            b1.Property<DateOnly>("BirthDate")
                                .HasColumnType("date")
                                .HasColumnName("BirthDate");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("Name");

                            b1.HasKey("AthleteId");

                            b1.ToTable("Athletes");

                            b1.WithOwner()
                                .HasForeignKey("AthleteId");
                        });

                    b.OwnsOne("NextStep.Domain.AthleteProfile.ValueObjects.PhysiologicalData", "PhysiologicalData", b1 =>
                        {
                            b1.Property<Guid>("AthleteId")
                                .HasColumnType("char(36)");

                            b1.Property<int?>("LactateThresholdHeartRate")
                                .HasColumnType("int")
                                .HasColumnName("LactateThresholdHeartRate");

                            b1.Property<TimeSpan?>("LactateThresholdPace")
                                .HasColumnType("time(6)")
                                .HasColumnName("LactateThresholdPace");

                            b1.Property<int?>("MaxHeartRate")
                                .HasColumnType("int")
                                .HasColumnName("MaxHeartRate");

                            b1.HasKey("AthleteId");

                            b1.ToTable("Athletes");

                            b1.WithOwner()
                                .HasForeignKey("AthleteId");
                        });

                    b.OwnsOne("NextStep.Domain.AthleteProfile.ValueObjects.TrainingAccess", "TrainingAccess", b1 =>
                        {
                            b1.Property<Guid>("AthleteId")
                                .HasColumnType("char(36)");

                            b1.Property<bool>("HasTrackAccess")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("tinyint(1)")
                                .HasDefaultValue(false)
                                .HasColumnName("HasTrackAccess");

                            b1.HasKey("AthleteId");

                            b1.ToTable("Athletes");

                            b1.WithOwner()
                                .HasForeignKey("AthleteId");
                        });

                    b.OwnsOne("NextStep.Domain.AthleteProfile.ValueObjects.TrainingAvailability", "TrainingAvailability", b1 =>
                        {
                            b1.Property<Guid>("AthleteId")
                                .HasColumnType("char(36)");

                            b1.Property<int>("Friday")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(0)
                                .HasColumnName("AvailabilityFriday");

                            b1.Property<int>("Monday")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(0)
                                .HasColumnName("AvailabilityMonday");

                            b1.Property<int>("Saturday")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(0)
                                .HasColumnName("AvailabilitySaturday");

                            b1.Property<int>("Sunday")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(0)
                                .HasColumnName("AvailabilitySunday");

                            b1.Property<int>("Thursday")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(0)
                                .HasColumnName("AvailabilityThursday");

                            b1.Property<int>("Tuesday")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(0)
                                .HasColumnName("AvailabilityTuesday");

                            b1.Property<int>("Wednesday")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(0)
                                .HasColumnName("AvailabilityWednesday");

                            b1.HasKey("AthleteId");

                            b1.ToTable("Athletes");

                            b1.WithOwner()
                                .HasForeignKey("AthleteId");
                        });

                    b.Navigation("PersonalInfo")
                        .IsRequired();

                    b.Navigation("PhysiologicalData")
                        .IsRequired();

                    b.Navigation("TrainingAccess")
                        .IsRequired();

                    b.Navigation("TrainingAvailability")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
