// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NextStep.Infrastructure.Persistence;

#nullable disable

namespace NextStep.Infrastructure.Migrations
{
    [DbContext(typeof(NextStepDbContext))]
    [Migration("20260201143045_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("NextStep.Domain.AthleteProfile.Entities.Athlete", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Athletes", (string)null);
                });

            modelBuilder.Entity("NextStep.Domain.AthleteProfile.Entities.Athlete", b =>
                {
                    b.OwnsMany("NextStep.Domain.AthleteProfile.ValueObjects.HeartRateZone", "HeartRateZones", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("AthleteId")
                                .HasColumnType("char(36)");

                            b1.Property<int>("MaxBpm")
                                .HasColumnType("int")
                                .HasColumnName("MaxBpm");

                            b1.Property<int>("MinBpm")
                                .HasColumnType("int")
                                .HasColumnName("MinBpm");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("Name");

                            b1.Property<int>("ZoneNumber")
                                .HasColumnType("int")
                                .HasColumnName("ZoneNumber");

                            b1.HasKey("Id");

                            b1.HasIndex("AthleteId");

                            b1.ToTable("HeartRateZones", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AthleteId");
                        });

                    b.OwnsMany("NextStep.Domain.AthleteProfile.ValueObjects.PaceZone", "PaceZones", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("AthleteId")
                                .HasColumnType("char(36)");

                            b1.Property<TimeSpan>("MaxPacePerKm")
                                .HasColumnType("time(6)")
                                .HasColumnName("MaxPacePerKm");

                            b1.Property<TimeSpan>("MinPacePerKm")
                                .HasColumnType("time(6)")
                                .HasColumnName("MinPacePerKm");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("Name");

                            b1.Property<int>("ZoneNumber")
                                .HasColumnType("int")
                                .HasColumnName("ZoneNumber");

                            b1.HasKey("Id");

                            b1.HasIndex("AthleteId");

                            b1.ToTable("PaceZones", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AthleteId");
                        });

                    b.OwnsOne("NextStep.Domain.AthleteProfile.ValueObjects.PersonalInfo", "PersonalInfo", b1 =>
                        {
                            b1.Property<Guid>("AthleteId")
                                .HasColumnType("char(36)");

                            b1.Property<DateOnly>("BirthDate")
                                .HasColumnType("date")
                                .HasColumnName("BirthDate");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("Name");

                            b1.HasKey("AthleteId");

                            b1.ToTable("Athletes");

                            b1.WithOwner()
                                .HasForeignKey("AthleteId");
                        });

                    b.OwnsOne("NextStep.Domain.AthleteProfile.ValueObjects.PhysiologicalData", "PhysiologicalData", b1 =>
                        {
                            b1.Property<Guid>("AthleteId")
                                .HasColumnType("char(36)");

                            b1.Property<int?>("LactateThreshold")
                                .HasColumnType("int")
                                .HasColumnName("LactateThreshold");

                            b1.Property<int?>("MaxHeartRate")
                                .HasColumnType("int")
                                .HasColumnName("MaxHeartRate");

                            b1.HasKey("AthleteId");

                            b1.ToTable("Athletes");

                            b1.WithOwner()
                                .HasForeignKey("AthleteId");
                        });

                    b.OwnsOne("NextStep.Domain.AthleteProfile.ValueObjects.TrainingAccess", "TrainingAccess", b1 =>
                        {
                            b1.Property<Guid>("AthleteId")
                                .HasColumnType("char(36)");

                            b1.Property<bool>("HasTrackAccess")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("tinyint(1)")
                                .HasDefaultValue(false)
                                .HasColumnName("HasTrackAccess");

                            b1.HasKey("AthleteId");

                            b1.ToTable("Athletes");

                            b1.WithOwner()
                                .HasForeignKey("AthleteId");
                        });

                    b.Navigation("HeartRateZones");

                    b.Navigation("PaceZones");

                    b.Navigation("PersonalInfo")
                        .IsRequired();

                    b.Navigation("PhysiologicalData")
                        .IsRequired();

                    b.Navigation("TrainingAccess")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
